# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.rcParams['figure.figsize'] = (10,8)

from projectile import *

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny.express import render, ui

    ui.input_numeric("dt","time step",value=0.1,step=0.0005,min=0.0005)
    ui.input_numeric("vLaunch","Launch Velocity",value=50,min=0,step=1)
    ui.input_numeric("theta","Launch Angle",value=10,step=1)
    ui.input_numeric("mass","Cannonball Mass",value=1,min=0,step=0.1)
    ui.input_numeric("coef","Drag Coef",value=0.0029,min=0,step=0.0001)
    ui.input_numeric("H","Cliff height",value=100,min=0)

    # ========================================================================

    @render.plot
    def displot():
      genProjectilePlot(0,input.H(),input.vLaunch(),
      input.theta(), input.dt(), 
      input.mass(), input.coef())

    # ========================================================================



    return None


_static_assets = ["projectile_files","projectile_files/libs/quarto-html/tippy.css","projectile_files/libs/quarto-html/quarto-syntax-highlighting.css","projectile_files/libs/bootstrap/bootstrap-icons.css","projectile_files/libs/bootstrap/bootstrap.min.css","projectile_files/libs/quarto-dashboard/datatables.min.css","projectile_files/libs/clipboard/clipboard.min.js","projectile_files/libs/quarto-html/quarto.js","projectile_files/libs/quarto-html/popper.min.js","projectile_files/libs/quarto-html/tippy.umd.min.js","projectile_files/libs/quarto-html/anchor.min.js","projectile_files/libs/bootstrap/bootstrap.min.js","projectile_files/libs/quarto-dashboard/quarto-dashboard.js","projectile_files/libs/quarto-dashboard/stickythead.js","projectile_files/libs/quarto-dashboard/datatables.min.js","projectile_files/libs/quarto-dashboard/pdfmake.min.js","projectile_files/libs/quarto-dashboard/vfs_fonts.js","projectile_files/libs/quarto-dashboard/web-components.js","projectile_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "projectile.html",
    server,
    static_assets=_static_assets,
)
